services:
  luye_api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always

  luye_simulator:
    build: .
    command: python simulator.py  # 启动模拟器的命令
    depends_on:
      - luye_api  # 告诉系统：等 API 启动了，再启动模拟器
    restart: always